version: '2'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
      PGDATA: /postgresql/data
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5431:5432
    restart: always